file_format: "1"
id: nmortho48
name: The nmortho48 
type: shield
url: https://github.com/benvallack/zmk-config-nmortho48
requires: [pro_micro]
exposes: [i2c_oled]
features:
  - keys
siblings:
  - nmortho48_left
  - nmortho48_right
  - nmortho48_dongle
